name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        run: |
          REPOSITORY_URI=213899591783.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic
          IMAGE_TAG=latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $REPOSITORY_URI:$IMAGE_TAG --push .

      - name: Output image digest
        run: echo "Image Digest: ${{ steps.build-image.outputs.digest }}"
